import type { SchemaIR, TableDef, ColumnDef } from './jsonAnalyzer';

// --- PostgreSQL DDL Generator ---
export function generatePostgreSQL(ir: SchemaIR): string {
  const lines: string[] = ['-- Generated by SchemaGen AI', `-- Tables detected: ${ir.tables.length}`, ''];

  for (const table of ir.tables) {
    lines.push(`CREATE TABLE ${table.name} (`);
    const colDefs: string[] = [];

    for (const col of table.columns) {
      let def = `  ${col.name} ${col.pgType}`;
      if (col.primaryKey && col.pgType === 'SERIAL') def = `  ${col.name} SERIAL PRIMARY KEY`;
      else if (col.primaryKey) def += ' PRIMARY KEY';
      if (col.unique && !col.primaryKey) def += ' UNIQUE';
      if (!col.nullable && !col.primaryKey) def += ' NOT NULL';
      if (col.default) def += ` DEFAULT ${col.default}`;
      if (col.foreignKey) def += ` REFERENCES ${col.foreignKey.table}(${col.foreignKey.column}) ON DELETE CASCADE`;
      if (col.enum && col.enum.length > 0) def += ` CHECK (${col.name} IN (${col.enum.map(e => `'${e}'`).join(', ')}))`;
      colDefs.push(def);
    }

    lines.push(colDefs.join(',\n'));
    lines.push(');');
    lines.push('');
  }

  // Index suggestions
  const allIndexes = ir.tables.flatMap(t => t.indexes);
  if (allIndexes.length > 0) {
    lines.push('-- Index suggestions (AI-recommended)');
    for (const idx of allIndexes) {
      lines.push(`CREATE INDEX idx_${idx.table}_${idx.column} ON ${idx.table}(${idx.column});`);
    }
  }

  return lines.join('\n');
}

// --- Mongoose Schema Generator ---
function mongooseType(col: ColumnDef): string {
  if (col.foreignKey) return `mongoose.Schema.Types.ObjectId`;
  return col.mongoType;
}

export function generateMongoose(ir: SchemaIR): string {
  const lines: string[] = [
    '// Generated by SchemaGen AI',
    "const mongoose = require('mongoose');",
    '',
  ];

  for (const table of ir.tables) {
    const modelName = capitalize(singularize(table.name));
    const schemaName = `${modelName}Schema`;

    lines.push(`const ${schemaName} = new mongoose.Schema({`);

    const colLines: string[] = [];
    for (const col of table.columns) {
      if (col.name === 'id' || col.name === '_id') continue; // MongoDB handles _id

      const props: string[] = [];
      props.push(`type: ${mongooseType(col)}`);
      if (col.foreignKey) props.push(`ref: '${capitalize(singularize(col.foreignKey.table))}'`);
      if (!col.nullable) props.push('required: true');
      if (col.unique) props.push('unique: true');
      if (col.index) props.push('index: true');
      if (col.enum && col.enum.length > 0) props.push(`enum: [${col.enum.map(e => `'${e}'`).join(', ')}]`);
      if (col.default === 'NOW()') props.push('default: Date.now');
      if (col.maxLength) props.push(`maxlength: ${col.maxLength}`);

      colLines.push(`  ${toCamelCase(col.name)}: { ${props.join(', ')} }`);
    }

    lines.push(colLines.join(',\n'));
    lines.push('});');
    lines.push('');
  }

  // Exports
  lines.push('module.exports = {');
  for (const table of ir.tables) {
    const modelName = capitalize(singularize(table.name));
    lines.push(`  ${modelName}: mongoose.model('${modelName}', ${modelName}Schema),`);
  }
  lines.push('};');

  return lines.join('\n');
}

// --- Prisma Schema Generator ---
export function generatePrisma(ir: SchemaIR): string {
  const lines: string[] = [
    '// Generated by SchemaGen AI',
    '',
    'generator client {',
    '  provider = "prisma-client-js"',
    '}',
    '',
    'datasource db {',
    '  provider = "postgresql"',
    '  url      = env("DATABASE_URL")',
    '}',
    '',
  ];

  for (const table of ir.tables) {
    const modelName = capitalize(singularize(table.name));
    lines.push(`model ${modelName} {`);

    for (const col of table.columns) {
      let line = `  ${toCamelCase(col.name)}`;
      
      if (col.foreignKey) {
        const refModel = capitalize(singularize(col.foreignKey.table));
        // Add the scalar field
        line += ` Int`;
        if (col.unique) line += ' @unique';
        lines.push(line);
        // Add the relation field
        const relationName = toCamelCase(col.name).replace(/Id$/, '');
        lines.push(`  ${relationName} ${refModel} @relation(fields: [${toCamelCase(col.name)}], references: [${col.foreignKey.column}])`);
        continue;
      }

      line += ` ${col.prismaType}`;
      if (col.primaryKey) {
        line += ' @id';
        if (col.autoIncrement) line += ' @default(autoincrement())';
      }
      if (col.unique && !col.primaryKey) line += ' @unique';
      if (col.nullable) line += '?';
      if (col.default === 'NOW()') line += ' @default(now())';

      lines.push(line);
    }

    // Add relation arrays from other tables pointing here
    for (const otherTable of ir.tables) {
      if (otherTable.name === table.name) continue;
      const fkCols = otherTable.columns.filter(c => c.foreignKey?.table === table.name);
      if (fkCols.length > 0) {
        const otherModel = capitalize(singularize(otherTable.name));
        lines.push(`  ${toCamelCase(otherTable.name)} ${otherModel}[]`);
      }
    }

    // Indexes
    const tableIndexes = table.indexes.filter(i => !table.columns.find(c => c.name === i.column && (c.primaryKey || c.unique)));
    if (tableIndexes.length > 0) {
      for (const idx of tableIndexes) {
        lines.push(`  @@index([${toCamelCase(idx.column)}])`);
      }
    }

    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

// --- Helpers ---
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function singularize(str: string): string {
  if (str.endsWith('ies')) return str.slice(0, -3) + 'y';
  if (str.endsWith('ses')) return str.slice(0, -2);
  if (str.endsWith('s') && !str.endsWith('ss')) return str.slice(0, -1);
  return str;
}

function toCamelCase(str: string): string {
  return str.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}
