import type { SchemaIR, TableDef, ColumnDef } from './jsonAnalyzer';

// --- PostgreSQL DDL Generator ---
export function generatePostgreSQL(ir: SchemaIR): string {
  const lines: string[] = ['-- Generated by SchemaGen AI', `-- Tables detected: ${ir.tables.length}`, ''];

  for (const table of ir.tables) {
    lines.push(`CREATE TABLE ${table.name} (`);
    const colDefs: string[] = [];

    for (const col of table.columns) {
      let def = `  ${col.name} ${col.pgType}`;
      if (col.primaryKey && col.pgType === 'SERIAL') def = `  ${col.name} SERIAL PRIMARY KEY`;
      else if (col.primaryKey) def += ' PRIMARY KEY';
      if (col.unique && !col.primaryKey) def += ' UNIQUE';
      if (!col.nullable && !col.primaryKey) def += ' NOT NULL';
      if (col.default !== undefined) {
        const isNum = !isNaN(Number(col.default)) && col.default.trim() !== '';
        def += ` DEFAULT ${isNum ? col.default : col.default}`;
      }
      if (col.foreignKey) def += ` REFERENCES ${col.foreignKey.table}(${col.foreignKey.column}) ON DELETE CASCADE`;
      if (col.enum && col.enum.length > 0) def += ` CHECK (${col.name} IN (${col.enum.map(e => `'${e}'`).join(', ')}))`;
      colDefs.push(def);
    }

    lines.push(colDefs.join(',\n'));
    lines.push(');');
    lines.push('');
  }

  // Index suggestions — skip columns already covered by PK or UNIQUE
  const allIndexes = ir.tables.flatMap(t => {
    const pkAndUniqueCols = new Set(t.columns.filter(c => c.primaryKey || c.unique).map(c => c.name));
    return t.indexes.filter(idx => !pkAndUniqueCols.has(idx.column));
  });
  if (allIndexes.length > 0) {
    lines.push('-- Index suggestions (AI-recommended)');
    for (const idx of allIndexes) {
      lines.push(`CREATE INDEX idx_${idx.table}_${idx.column} ON ${idx.table}(${idx.column});`);
    }
  }

  return lines.join('\n');
}

// --- Mongoose Schema Generator ---
function mongooseType(col: ColumnDef): string {
  if (col.foreignKey) return `mongoose.Schema.Types.ObjectId`;
  if (col.type === 'decimal') return 'mongoose.Schema.Types.Decimal128';
  return col.mongoType;
}

export function generateMongoose(ir: SchemaIR): string {
  const lines: string[] = [
    '// Generated by SchemaGen AI',
    "const mongoose = require('mongoose');",
    '',
  ];

  for (const table of ir.tables) {
    const modelName = capitalize(singularize(table.name));
    const schemaName = `${modelName}Schema`;

    lines.push(`const ${schemaName} = new mongoose.Schema({`);

    const colLines: string[] = [];
    const hasLifecycleFields = table.columns.some(c => c.name === 'created_at' || c.name === 'updated_at');

    for (const col of table.columns) {
      if (col.name === 'id' || col.name === '_id') continue; // MongoDB handles _id
      // Skip lifecycle fields — Mongoose handles them with { timestamps: true }
      if (hasLifecycleFields && (col.name === 'created_at' || col.name === 'updated_at')) continue;

      const props: string[] = [];
      props.push(`type: ${mongooseType(col)}`);
      if (col.foreignKey) props.push(`ref: '${capitalize(singularize(col.foreignKey.table))}'`);
      if (!col.nullable) props.push('required: true');
      if (col.unique) props.push('unique: true');
      if (col.index) props.push('index: true');
      if (col.enum && col.enum.length > 0) props.push(`enum: [${col.enum.map(e => `'${e}'`).join(', ')}]`);
      if (col.default === 'NOW()') {
        props.push('default: Date.now');
      } else if (col.default !== undefined) {
        const isNum = !isNaN(Number(col.default)) && col.default.trim() !== '';
        props.push(`default: ${isNum ? col.default : `'${col.default}'`}`);
      }
      if (col.maxLength && !col.foreignKey && col.type !== 'enum') {
        props.push(`maxlength: ${col.maxLength}`);
      }

      colLines.push(`  ${toCamelCase(col.name)}: { ${props.join(', ')} }`);
    }

    lines.push(colLines.join(',\n'));
    if (hasLifecycleFields) {
      lines.push('}, { timestamps: { createdAt: \'created_at\', updatedAt: \'updated_at\' } });');
    } else {
      lines.push('});');
    }
    lines.push('');
  }

  // Exports
  lines.push('module.exports = {');
  for (const table of ir.tables) {
    const modelName = capitalize(singularize(table.name));
    lines.push(`  ${modelName}: mongoose.model('${modelName}', ${modelName}Schema),`);
  }
  lines.push('};');

  return lines.join('\n');
}

// --- Prisma Schema Generator ---
export function generatePrisma(ir: SchemaIR): string {
  const lines: string[] = [
    '// Generated by SchemaGen AI',
    '',
    'generator client {',
    '  provider = "prisma-client-js"',
    '}',
    '',
    'datasource db {',
    '  provider = "postgresql"',
    '  url      = env("DATABASE_URL")',
    '}',
    '',
  ];

  for (const table of ir.tables) {
    const modelName = capitalize(singularize(table.name));
    lines.push(`model ${modelName} {`);

    for (const col of table.columns) {
      let line = `  ${toCamelCase(col.name)}`;
      
      if (col.foreignKey) {
        const refModel = capitalize(singularize(col.foreignKey.table));
        // Use the correct scalar type from the IR instead of always Int
        line += ` ${col.prismaType}`;
        if (col.unique) line += ' @unique';
        lines.push(line);
        // Add the relation field
        const relationName = toCamelCase(col.name).replace(/Id$/, '');
        lines.push(`  ${relationName} ${refModel} @relation(fields: [${toCamelCase(col.name)}], references: [${col.foreignKey.column}])`);
        continue;
      }

      line += ` ${col.prismaType}`;
      if (col.primaryKey) {
        line += ' @id';
        if (col.autoIncrement) line += ' @default(autoincrement())';
        if (col.type === 'uuid') line += ' @default(uuid())';
      }
      if (col.unique && !col.primaryKey) line += ' @unique';
      if (col.nullable) line += '?';
      if (col.default === 'NOW()') {
        if (col.name === 'updated_at') {
          line += ' @updatedAt';
        } else {
          line += ' @default(now())';
        }
      } else if (col.default !== undefined && !col.primaryKey) {
        const isNum = !isNaN(Number(col.default)) && col.default.trim() !== '';
        line += ` @default(${isNum ? col.default : `"${col.default}"`})`;
      }

      lines.push(line);
    }

    // Add relation arrays (or single fields for 1:1) from other tables pointing here
    for (const otherTable of ir.tables) {
      if (otherTable.name === table.name) continue;
      const fkCols = otherTable.columns.filter(c => c.foreignKey?.table === table.name);
      for (const fkCol of fkCols) {
        const otherModel = capitalize(singularize(otherTable.name));
        const fieldName = toCamelCase(otherTable.name);
        if (fkCol.unique) {
          lines.push(`  ${singularize(fieldName)} ${otherModel}?`);
        } else {
          lines.push(`  ${fieldName} ${otherModel}[]`);
        }
      }
    }

    // Indexes
    const tableIndexes = table.indexes.filter(i => !table.columns.find(c => c.name === i.column && (c.primaryKey || c.unique)));
    if (tableIndexes.length > 0) {
      for (const idx of tableIndexes) {
        lines.push(`  @@index([${toCamelCase(idx.column)}])`);
      }
    }

    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

// --- Drizzle Schema Generator ---
export function generateDrizzle(ir: SchemaIR): string {
  const lines: string[] = [
    '// Generated by SchemaGen AI',
    "import { pgTable, serial, text, varchar, timestamp, integer, boolean, numeric, uuid, jsonb, pgEnum } from 'drizzle-orm/pg-core';",
    "import { relations } from 'drizzle-orm';",
    '',
  ];

  // Enums
  const enumsSeen = new Set<string>();
  for (const table of ir.tables) {
    for (const col of table.columns) {
      if (col.type === 'enum' && col.enum) {
        const enumName = `${toCamelCase(col.name)}Enum`;
        if (!enumsSeen.has(enumName)) {
          lines.push(`export const ${enumName} = pgEnum('${col.name}', [${col.enum.map(e => `'${e}'`).join(', ')}]);`);
          enumsSeen.add(enumName);
        }
      }
    }
  }
  if (enumsSeen.size > 0) lines.push('');

  for (const table of ir.tables) {
    const tableName = table.name;
    const variableName = toCamelCase(table.name);
    
    lines.push(`export const ${variableName} = pgTable('${tableName}', {`);
    
    const colLines: string[] = [];
    for (const col of table.columns) {
      let colDef = `  ${toCamelCase(col.name)}: `;
      
      if (col.primaryKey && col.pgType === 'SERIAL') {
        colDef += `serial('${col.name}')`;
      } else if (col.type === 'enum' && col.enum) {
        const enumName = `${toCamelCase(col.name)}Enum`;
        colDef += `${enumName}('${col.name}')`;
      } else {
        switch (col.type) {
          case 'integer': colDef += `integer('${col.name}')`; break;
          case 'string': colDef += `varchar('${col.name}', { length: ${col.maxLength || 255} })`; break;
          case 'text': colDef += `text('${col.name}')`; break;
          case 'boolean': colDef += `boolean('${col.name}')`; break;
          case 'decimal': colDef += `numeric('${col.name}', { precision: 10, scale: 2 })`; break;
          case 'date': colDef += `timestamp('${col.name}', { withTimezone: true })`; break;
          case 'uuid': colDef += `uuid('${col.name}')`; break;
          case 'mixed': colDef += `jsonb('${col.name}')`; break;
          case 'email': colDef += `varchar('${col.name}', { length: 255 })`; break;
          default: colDef += `text('${col.name}')`;
        }
      }

      if (col.primaryKey) {
        colDef += '.primaryKey()';
        if (col.type === 'uuid') colDef += '.defaultRandom()';
      }
      if (!col.nullable && !col.primaryKey) colDef += '.notNull()';
      if (col.unique && !col.primaryKey) colDef += '.unique()';
      
      if (col.default === 'NOW()') {
        colDef += '.defaultNow()';
        if (col.name === 'updated_at') colDef += '.$onUpdate(() => new Date())';
      } else if (col.default !== undefined) {
        const isNum = !isNaN(Number(col.default)) && col.default.trim() !== '';
        colDef += `.default(${isNum ? col.default : `'${col.default}'`})`;
      }

      if (col.foreignKey) {
        const refTableVar = toCamelCase(col.foreignKey.table);
        colDef += `.references(() => ${refTableVar}.${col.foreignKey.column})`;
      }

      colLines.push(colDef);
    }
    
    lines.push(colLines.join(',\n'));
    lines.push('});');
    lines.push('');
  }

  // Relations
  for (const table of ir.tables) {
    const variableName = toCamelCase(table.name);
    const relationsList: string[] = [];
    
    // belongsTo
    for (const col of table.columns) {
      if (col.foreignKey) {
        const refTableVar = toCamelCase(col.foreignKey.table);
        const relationName = toCamelCase(col.name).replace(/Id$/, '');
        relationsList.push(`  ${relationName}: one(${refTableVar}, { fields: [${variableName}.${toCamelCase(col.name)}], references: [${refTableVar}.${col.foreignKey.column}] })`);
      }
    }
    
    // hasMany or hasOne
    for (const otherTable of ir.tables) {
      if (otherTable.name === table.name) continue;
      const fkCols = otherTable.columns.filter(c => c.foreignKey?.table === table.name);
      for (const fkCol of fkCols) {
        const otherTableVar = toCamelCase(otherTable.name);
        if (fkCol.unique) {
          // 1:1 relation
          const singularName = singularize(otherTableVar);
          relationsList.push(`  ${singularName}: one(${otherTableVar})`);
        } else {
          // 1:N relation
          relationsList.push(`  ${otherTableVar}: many(${otherTableVar})`);
        }
      }
    }
    
    if (relationsList.length > 0) {
      lines.push(`export const ${variableName}Relations = relations(${variableName}, ({ one, many }) => ({`);
      lines.push(relationsList.join(',\n'));
      lines.push('}));');
      lines.push('');
    }
  }

  return lines.join('\n');
}

// --- Helpers ---
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function singularize(str: string): string {
  if (str.endsWith('ies')) return str.slice(0, -3) + 'y';
  if (str.endsWith('ses')) return str.slice(0, -2);
  if (str.endsWith('s') && !str.endsWith('ss')) return str.slice(0, -1);
  return str;
}

function toCamelCase(str: string): string {
  return str.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}
